<?php

// $Id: shoutcast.module,v 1.10.2.1 2010/08/22 23:04:42 yohnson Exp $

/**
 * Display help and module information
 *
 * @param  string  $path    Path to display help for
 * @param  array   $arg     Holds the current path returned from arg() function
 * @return string  $output  Help text for the path
 */
function shoutcast_help($path, $arg) {
  switch ($path) {
    case 'admin/help#shoutcast':
      $output = '<p>' . t('Displays SHOUTcast server statistics.') . '</p>';
      break;
    default:
      $output = '';
      break;
  }
  return $output;
}

/**
 * Valid permissions for this module
 *
 * @return array   Valid permissions list for the SHOUTcast stats module
 */
function shoutcast_perm() {
  return array('access shoutcast content', 'access administration pages');
}

/**
 * Generate the SHOUTcast admin settings form
 *
 * @return array   Module admin form
 *
 * @todo Enable the listeners option
 * @todo Add date format to display with song history in block and page
 */
function shoutcast_admin() {
  $form['shoutcast_ip'] = array(
      '#type' => 'textfield',
      '#title' => t('SHOUTcast Server URL'),
      '#default_value' => variable_get('shoutcast_ip', '127.0.0.1'),
      '#size' => 40,
      '#maxlength' => 255,
      '#description' => t('The URL of the SHOUTcast server, not including http://'),
      '#required' => TRUE,
  );

  $form['shoutcast_port'] = array(
      '#type' => 'textfield',
      '#title' => t('Server Port'),
      '#default_value' => variable_get('shoutcast_port', '8000'),
      '#size' => 4,
      '#maxlength' => 4,
      '#description' => t('SHOUTcast server port, normally 8000'),
      '#required' => TRUE,
  );

  $form['shoutcast_pw'] = array(
      '#type' => 'textfield',
      '#title' => t('Server Password for XML Stats'),
      '#default_value' => variable_get('shoutcast_pw', 'password'),
      '#size' => 20,
      '#maxlength' => 100,
      '#description' => t('Password of SHOUTcast server, normally set in sc_serv.conf'),
      '#required' => TRUE,
  );

  $form['shoutcast_cachetime'] = array(
      '#type' => 'select',
      '#title' => t('Cache Time'),
      '#default_value' => variable_get('shoutcast_cachetime', 1),
      '#options' => array(0, 1, 2, 4, 5, 10, 15, 30, 60),
      '#description' => t('Minutes between XML retrieval.')
  );

  $form['shoutcast_error_handling'] = array(
      '#type' => 'radios',
      '#title' => t('Error Handling'),
      '#default_value' => variable_get('shoutcast_error_handling', 0),
      '#options' => array(t('Do not display table'), t('Display table with error message')),
      '#description' => t('When SHOUTcast XML feed is unavaible or invalid.'),
  );

  $shoutcast_stats = array(
          'currentlisteners' => t('Current listeners'),
          'peaklisteners' => t('Peak listeners'),
          'maxlisteners' => t('Max listeners allowed'),
          'reportedlisteners' => t('Reported listeners'),
          'averagetime' => t('Average length of time people listen'),
          'servergenre' => t('Server genre'),
          'serverurl' => t('Server URL'),
          'servertitle' => t('Server Title'),
          'songtitle' => t('Display current song title'),
          //'songurl' => t('Song URL'), // object
          'irc' => t('IRC'),
          //'icq' => t('ICQ'), // object
          //'aim' => t('AIM'), // object
          'webhits' => t('Web hits'),
          'streamhits' => t('Stream hits'),
          'streamstatus' => t('Display server status'),
          'bitrate' => t('Stream bitrate'),
          'content' => t('Content type'),
          'version' => t('Server version'),
          //'webdata' => t('Web data'), // object
          //'listeners' => t('Listeners'), // object
          'songhistory' => t('Song history'), // object
      );

  $form['shoutcast_page_fields'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Page Display Options'),
      '#default_value' => variable_get('shoutcast_page_fields', array('currentlisteners',
            'peaklisteners', 'maxlisteners', 'reportedlisteners', 'averagetime', 'servergenre',
            'serverurl', 'servertitle', 'irc', 'webhits', 'streamhits', 'streamstatus', 'bitrate',
            'content', 'version', 'songhistory'
          )),
      '#options' => $shoutcast_stats
  );

  $form['shoutcast_block_subject'] = array(
      '#type' => 'textfield',
      '#title' => t('Block Title'),
      '#default_value' => variable_get('shoutcast_block_subject', 'Listener Stats'),
      '#size' => 25,
      '#maxlength' => 25,
      '#description' => t('The title displayed for the SHOUTcast Stats block.'),
      '#required' => TRUE,
  );

  $block_options = array_merge(
          array('details_link' => t('Show \'Details...\' link under block')),
          $shoutcast_stats
  );

  $form['shoutcast_block_options'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Block Display Options'),
      '#default_value' => variable_get('shoutcast_block_options', array('details_link',
            'currentlisteners', 'songtitle', 'streamstatus'
          )),
      '#options' => $block_options
  );

  return system_settings_form($form);
}

/**
 * Generate the menu items for shoutcast
 *
 * @return array   Menu items array
 */
function shoutcast_menu() {
  $items = array();

  $items['admin/settings/shoutcast'] = array(
      'title' => 'SHOUTcast Stats',
      'description' => 'Get stats from SHOUTcast server as a block',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shoutcast_admin'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
  );

  // this is added for this current tutorial.
  $items['shoutcast'] = array(
      'title' => 'SHOUTcast Stats',
      'page callback' => 'shoutcast_all',
      'access arguments' => array('access shoutcast content'),
      'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Generate HTML for the shoutcast block
 *
 * @param  string  $op     Current operation from the URL
 * @param  int     $delta  Offset for this block
 * @return string  $block  Block content, an HTML table
 */
function shoutcast_block($op = 'list', $delta = 0) {
  // listing of blocks, such as on the admin/block page
  if ($op == 'list') {
    $block[0]['info'] = t('SHOUTcast Stats');
    return $block;

  } elseif ($op == 'view') {
    // Get SHOUTcast XML data, either from the server or cache
    $xml = shoutcast_get_xml();
    $options = variable_get('shoutcast_block_options', array('details_link',
          'currentlisteners', 'songtitle', 'streamstatus'
      ));

    // build the block's table
    $header = array('Statistic', 'Value');
    $rows = shoutcast_table_rows($xml, $options);
    $attributes = array('id' => 'shoutcast-block-table');
    $block_content = theme('table', $header, $rows, $attributes);

    // when using checkboxes we have to cast the variable as a string
    if ((string) $options['details_link'] == 'details_link') {
      $block_content .= '<a href="' . url('shoutcast') . '">Details...</a>';
    }

    // set up the block
    $block['subject'] = variable_get('shoutcast_block_subject', 'SHOUTcast Stats');
    $block['content'] = $block_content;

    return $block;
  }
}

/**
 * Generate HTML for the SHOUTcast page
 *
 * @return string  $page   Page content, an HTML table
 */
function shoutcast_all() {
  // Get SHOUTcast XML data, either from the server or cache
  $xml = shoutcast_get_xml();
  $options = variable_get('shoutcast_page_fields', array('currentlisteners', 'peaklisteners',
      'maxlisteners', 'reportedlisteners', 'averagetime', 'servergenre', 'serverurl',
      'servertitle', 'irc', 'webhits', 'streamhits', 'streamstatus', 'bitrate',
      'content', 'version', 'songhistory'
      ));

  // Build the page's table
  $rows = shoutcast_table_rows($xml, $options);
  $header = array('Statistic', 'Value');
  $attributes = array('id' => 'shoutcast-node-table');
  $page = theme('table', $header, $rows, $attributes);

  return $page;
}

/**
 * Get SHOUTcast server details from its XML stats page
 *
 * @return object  $xml      An XML object containing all stats
 */
function shoutcast_get_xml() {
  // if the cache has expired or it doesn't exist, get stats from the server
  if ($xml_cache->expire < time() || !$xml_cache = cache_get('shoutcast')) {
    error_reporting(E_ALL ^ E_NOTICE);
    $host = variable_get('shoutcast_ip', '127.0.0.1');
    $port = variable_get('shoutcast_port', '8000');
    $password = variable_get('shoutcast_pw', 'password');
    $username = 'admin';
    $useragent = 'Mozilla/5.001 (Drupal SHOUTcast Stats Module)';
    $headers = array('User-Agent' => $useragent, 'Authorization' => 'Basic ' . base64_encode($username . ':' . $password));
    $response = drupal_http_request("http://$host:$port/admin.cgi?mode=viewxml", $headers, 'GET');
    $xml = simplexml_load_string($response->data);
    // Append the request response code to the object
    $xml->RESPONSECODE = $response->code;

    // get the caching interval (in minutes) from the module's settings
    $interval = variable_get('shoutcast_cachetime', 1);

    // update the cache
    cache_set('shoutcast', $xml_data, 'cache', time() + ($interval * 60));

  } else {
    // get cached data
    $xml = simplexml_load_string($xml_cache->data);
  }

  return $xml;
}

/**
 * Build a set of table rows for the stats table block and page
 *
 * @param  object  $xml      The SHOUTcast
 * @param  array   $options  SHOUTcast module settings, includes which fields to show
 * @return array   $row      List of table rows to display
 *
 * @todo Display listeners
 */
function shoutcast_table_rows($xml, $options) {
  $rows = array();
  $show_errors = variable_get('shoutcast_error_handling', 0);

  // If the module's set to display errors and a response code other than 200 OK, show errors
  if ($show_errors && ($xml->RESPONSECODE != 200)) {
      $rows[] = array(
          array('data' => 'Error'),
          array('data' => 'SHOUTcast module has not been configured or the server is not responding')
      );
      // SHOUTcast server response codes (HTTP), 200 OK
      switch ($xml->RESPONSECODE) {
        case 203:
          $response_code = '203 Partial Information';
          break;
        case 204:
          $response_code = '204 No Response';
          break;
        case 401:
          $response_code = '401 Unauthorized';
          break;
        case 403:
          $response_code = '403 Forbidden';
          break;
        case 404:
          $response_code = '404 Not found';
          break;
        case 500:
          $response_code = '500 Internal Error';
          break;
        case 503:
          $response_code = '503 Gateway timout';
          break;
        default:
          $response_code = $xml->RESPONSECODE . ' Unknown error';
          break;
      }
      $rows[] = array(
          array('data' => 'Response'),
          array('data' => $response_code)
      );

  } else {

    if ((string) $options['currentlisteners'] == 'currentlisteners') {
      $rows[] = array(
          array('data' => 'Current Listeners'),
          array('data' => $xml->CURRENTLISTENERS)
      );
    }
    if ((string) $options['peaklisteners'] == 'peaklisteners') {
      $rows[] = array(
          array('data' => 'Most Listeners'),
          array('data' => $xml->PEAKLISTENERS)
      );
    }
    if ((string) $options['maxlisteners'] == 'maxlisteners') {
      $rows[] = array(
          array('data' => 'Listener Limit'),
          array('data' => $xml->MAXLISTENERS)
      );
    }
    if ((string) $options['reportedlisteners'] == 'reportedlisteners') {
      $rows[] = array(
          array('data' => 'Reported Listeners'),
          array('data' => $xml->REPORTEDLISTENERS)
      );
    }
    if ((string) $options['averagetime'] == 'averagetime') {
      $avg = floor($xml->AVERAGETIME / 60);
      $rows[] = array(
          array('data' => 'Average Listen Time'),
          array('data' => $avg . ' minutes')
      );
    }
    if ((string) $options['servergenre'] == 'servergenre') {
      $rows[] = array(
          array('data' => 'Server Genre'),
          array('data' => $xml->SERVERGENRE)
      );
    }
    if ((string) $options['serverurl'] == 'serverurl') {
      $rows[] = array(
          array('data' => 'Server URL'),
          array('data' => '<a href="' . $xml->SERVERURL . '">' . $xml->SERVERURL . '</a>')
      );
    }
    if ((string) $options['servertitle'] == 'servertitle') {
      $rows[] = array(
          array('data' => 'Server Title'),
          array('data' => $xml->SERVERTITLE)
      );
    }
    if ((string) $options['songtitle'] == 'songtitle') {
      $rows[] = array(
          array('data' => 'Current Song'),
          array('data' => $xml->SONGTITLE)
      );
    }
    if ((string) $options['irc'] == 'irc') {
      $rows[] = array(
          array('data' => 'IRC'),
          array('data' => $xml->IRC)
      );
    }
    if ((string) $options['webhits'] == 'webhits') {
      $rows[] = array(
          array('data' => 'Web Hits'),
          array('data' => $xml->WEBHITS)
      );
    }
    if ((string) $options['streamhits'] == 'streamhits') {
      $rows[] = array(
          array('data' => 'Stream Hits'),
          array('data' => $xml->STREAMHITS)
      );
    }
    if ((string) $options['streamstatus'] == 'streamstatus') {
      ($xml->STREAMSTATUS == '1') ? $sc_srv_status = 'Up' : $sc_srv_status = 'Down';
      $rows[] = array(
          array('data' => 'Stream Status'),
          array('data' => $sc_srv_status)
      );
    }
    if ((string) $options['bitrate'] == 'bitrate') {
      $rows[] = array(
          array('data' => 'Stream Bitrate'),
          array('data' => $xml->BITRATE . ' kbps')
      );
    }
    if ((string) $options['content'] == 'content') {
      $rows[] = array(
          array('data' => 'Content Type'),
          array('data' => $xml->CONTENT)
      );
    }
    if ((string) $options['version'] == 'version') {
      $rows[] = array(
          array('data' => 'Version'),
          array('data' => $xml->VERSION)
      );
    }
    if ((string) $options['songhistory'] == 'songhistory') {
      $history = shoutcast_history_toarray($xml->SONGHISTORY);
      $rows[] = array(
          array('data' => 'Song History'),
          array('data' => shoutcast_history_format($history))
      );
    }
  }

  return $rows;
}

/**
 * Convert SHOUTcast XML song history object to an array, using played date as the key
 *
 * @param  object $songhistory  SHOUTcast XML SONGHISTORY object
 * @return array  $list         List of songs indexed by the song's played date
 */
function shoutcast_history_toarray($songhistory) {
  $list = array();
  if (count($songhistory->SONG)) {
    foreach ($songhistory->SONG as $k => $song) {
      $list[(int) $song->PLAYEDAT] = (string) $song->TITLE;
    }
  }
  return $list;
}

/**
 * Simple format of song history array as HTML
 *
 * @param  array   $history  Song list array, indexed by played date (unix timestamp)
 * @return string  $html     Song history in HTML format, each in a paragraph
 */
function shoutcast_history_format($history) {
  $html = '';
  if (count($history)) {
    foreach ($history as $timestamp => $song) {
      $date = format_date($timestamp, 'medium', '', 0);
      $html .= "<p>$date - $song</p>";
    }
  }

  return $html;
}
